/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{ts,tsx,js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Golos Text', 'Montserrat', 'system-ui', 'sans-serif'],
        golos: ['Golos Text', 'sans-serif'],
        montserrat: ['Montserrat', 'sans-serif'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          1: 'hsl(var(--chart-1))',
          2: 'hsl(var(--chart-2))',
          3: 'hsl(var(--chart-3))',
          4: 'hsl(var(--chart-4))',
          5: 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
        neutral: {
          50: '#f8fafc',
          100: '#f1f5f9',
          150: '#e2e8f0',
          200: '#cbd5e1',
          250: '#bfccd9',
          300: '#94a3b8',
          350: '#7e8da4',
          400: '#64748b',
          450: '#56657a',
          500: '#475569',
          550: '#3e4a5d',
          600: '#334155',
          650: '#263344',
          700: '#1e293b',
          750: '#162030',
          800: '#0f172a',
          850: '#0b1121',
          900: '#020617',
          950: '#01040f',
        },
        gray: {
          50: '#fafafa',
          100: '#f5f5f5',
          150: '#ebebeb',
          200: '#e5e5e5',
          250: '#dedede',
          300: '#d4d4d4',
          350: '#bcbcbc',
          400: '#a3a3a3',
          450: '#8a8a8a',
          500: '#737373',
          550: '#666666',
          600: '#525252',
          650: '#454545',
          700: '#404040',
          750: '#333333',
          800: '#262626',
          850: '#171717',
          900: '#0a0a0a',
          950: '#050505',
        },
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
