export enum UserRole {
  LEGAL = 'LEGAL',
  INDIVIDUAL = 'INDIVIDUAL',
  INSPECTOR = 'INSPECTOR',
  REGIONAL = 'REGIONAL',
  MANAGER = 'MANAGER',
  HEAD = 'HEAD',
  CHAIRMAN = 'CHAIRMAN',
  ADMIN = 'ADMIN',
}

export enum Permission {
  HF = 'HF',
  IRS = 'IRS',
  EQUIPMENT = 'EQUIPMENT',
  XRAY = 'XRAY',
  APPEAL = 'APPEAL',
  REGISTRY = 'REGISTRY',
  PREVENTION = 'PREVENTION',
  RISK_ANALYSIS = 'RISK_ANALYSIS',
  INSPECTION = 'INSPECTION',
  ATTESTATION_REGIONAL = 'ATTESTATION_REGIONAL',
  ATTESTATION_COMMITTEE = 'ATTESTATION_COMMITTEE',
  ACCREDITATION = 'ACCREDITATION',
  CADASTRE = 'CADASTRE',
  PERMITS = 'PERMITS',
  REPORT = 'REPORT',
  INQUIRY = 'INQUIRY',
}
